# Deployment role for Laravel apps.
# License: MIT
# 
# synchronize 
---
- name: RSync deploy.
  synchronize: 
    src: "/data/{{ env }}/{{ pname }}/releases/{{ release_version.stdout }}"
    dest: "/var/blob/{{ pname }}/releases"
    times: no 
    recursive: yes 
    perms: no 
    owner: no 
    group: no
    verify_host: true
    rsync_opts:
      - "--exclude=.git"
  register: sync
  ignore_errors: true

- name: Cleanup on Synchronize  failure for local
  file: path=/data/{{ env }}/{{ pname }}/releases/{{ release_version.stdout }} state=absent
  when: sync|failed

- fail: msg="Synchronize failed!"
  when: sync|failed